apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: udidfyi
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - udid.fyi
    - www.udid.fyi
    secretName: udid-cert
  rules:
  - host: udid.fyi
    http:
      paths:
      - backend:
          serviceName: udidfyi
          servicePort: 80
  - host: www.udid.fyi
    http:
      paths:
      - backend:
          serviceName: udidfyi
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: udidfyi
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8001
  selector:
    app: udidfyi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udidfyi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udidfyi
  template:
    metadata:
      labels:
        app: udidfyi
    spec:
      containers:
      - name: udidfyi
        image: registry.digitalocean.com/mattmalone/udidfyi@sha256:536d189ad5a02ef0e2f75655aeb4b109877d2b4ce48a0cd511fa9ec742561e52
        ports:
        - containerPort: 8001
      imagePullSecrets:
      - name: mattmalone